[package]
name = "kumo-wreq-stealth-spike"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
async-trait = "0.1.89"
bytes = "1.11.1"
reqwest = { version = "0.13.2", default-features = false }
tokio = { version = "1.52.1", features = ["macros", "rt-multi-thread"] }
wreq = { version = "5.3.0", default-features = false, features = [
  "brotli",
  "cookies",
  "deflate",
  "gzip",
  "zstd",
] }
wreq-util = "2.2.6"
